## Importing the Libraries

In [35]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
import warnings
warnings.filterwarnings('ignore')
from sklearn.preprocessing import OneHotEncoder,LabelEncoder
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor

## Importing the Dataset

In [36]:
df = pd.read_csv(r"C:\Users\hi\Downloads\Cars.csv")

In [37]:
df.head()

HP        MPG  VOL          SP         WT
0  49  53.700681   89  104.185353  28.762059
1  55  50.013401   92  105.461264  30.466833
2  55  50.013401   92  105.461264  30.193597
3  70  45.696322   92  113.461264  30.632114
4  53  50.504232   92  104.461264  29.889149

### Business Objective : Maximize the Mileage
    
### Constraints: Minimize the Features

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 81 entries, 0 to 80
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   HP      81 non-null     int64  
 1   MPG     81 non-null     float64
 2   VOL     81 non-null     int64  
 3   SP      81 non-null     float64
 4   WT      81 non-null     float64
dtypes: float64(3), int64(2)
memory usage: 3.3 KB


In [39]:
df.isna().sum()

HP     0
MPG    0
VOL    0
SP     0
WT     0
dtype: int64

In [40]:
df.duplicated().sum()

0

In [41]:
df.columns

Index(['HP', 'MPG', 'VOL', 'SP', 'WT'], dtype='object')

In [42]:
X = df[['HP', 'VOL', 'SP', 'WT']] # input variable
y = df[['MPG']] # target variable

## Splitting the data into train and test


In [43]:
X_train,X_test,y_train,y_test = train_test_split(X,y,train_size = 0.8,random_state = 4)

In [44]:
X_train,X_test,y_train,y_test

(     HP  VOL          SP         WT
 16   78   91  114.369293  29.535784
 39  130   92  128.461264  30.115434
 29  103  107  121.840817  35.549360
 10   73   89  111.185353  29.363341
 13   73   89  111.185353  29.378436
 ..  ...  ...         ...        ...
 72  162  132  133.140074  43.353123
 1    55   92  105.461264  30.466833
 69  245  112  158.300669  37.141733
 55  130  124  126.404312  40.589068
 46  100  111  118.208698  36.498617
 
 [64 rows x 4 columns],
      HP  VOL          SP         WT
 77  238  115  150.576579  37.923113
 26   92  117  120.760520  38.062823
 78  263   50  151.598513  15.769625
 20   92   99  119.105055  32.324650
 19   90  103  118.472936  33.516974
 68  165  123  133.312342  40.472042
 67  165  127  133.680223  41.573975
 63  140  123  125.312342  40.722831
 5    70   89  113.185353  29.591768
 35   90   98  115.013085  31.911223
 51  115  101  118.288996  33.436711
 45  100   99  117.105055  32.621916
 60  145  111  130.208698  36.888153
 14   66   8

# Model Building

## Linear Regression

In [45]:
reg = LinearRegression()

In [46]:
reg.fit(X_train,y_train)

LinearRegression()

In [56]:
reg.predict([[78,91,120,30]])

array([[43.59582659]])

In [57]:
reg.intercept_

array([28.52485307])

In [58]:
reg.coef_

array([[-0.20984765, -0.68233387,  0.40840972,  1.48407688]])

## Model Evaluation

In [64]:
y_pred = reg.predict(X_test)

In [65]:
y_pred,y_test

(array([[17.89047103],
        [35.19373233],
        [24.53586978],
        [38.28374332],
        [37.48544081],
        [24.48260285],
        [23.53886592],
        [26.83370618],
        [43.2502602 ],
        [37.10101567],
        [33.40967771],
        [36.22930856],
        [30.2812371 ],
        [41.6847613 ],
        [39.04124537],
        [41.64900106],
        [28.42955288]]),
           MPG
 77  19.197888
 26  38.411003
 78  34.000000
 20  38.411003
 19  38.901834
 68  23.103172
 67  23.103172
 63  23.515917
 5   45.696322
 35  37.958743
 51  29.629936
 45  34.561499
 60  27.354265
 14  45.734893
 27  38.411003
 4   50.504232
 54  26.852279)

In [66]:
mean_squared_error(y_pred,y_test)

14.518263261905178

In [67]:
np.sqrt(mean_squared_error(y_pred,y_test))

3.810283882062487

In [60]:
reg = LinearRegression()
reg.fit(X_train,y_train)                              
y_pred = reg.predict(X_test)
mean_squared_error(y_pred,y_test)
np.sqrt(mean_squared_error(y_pred,y_test))

3.810283882062487

## KNN Regression

In [61]:
knn = KNeighborsRegressor()
knn.fit(X_train,y_train)  
y_pred = knn.predict(X_test)
mean_squared_error(y_pred,y_test)
np.sqrt(mean_squared_error(y_pred,y_test))

3.530800624034759

## Decision Tree

In [62]:
dt = DecisionTreeRegressor()
dt.fit(X_train,y_train)                               
y_pred = dt.predict(X_test)
mean_squared_error(y_pred,y_test)
np.sqrt(mean_squared_error(y_pred,y_test))

4.113358046047767

## Random Forest

In [63]:
rf = RandomForestRegressor()
rf.fit(X_train,y_train)                              
y_pred = rf.predict(X_test)
mean_squared_error(y_pred,y_test)
np.sqrt(mean_squared_error(y_pred,y_test))

2.9311679390335525