1. clean the data(outlier,missing values,type conversion)

2. What is the mean value of sepal length

3. sort the sepal width in ascending order.

4. apply all statistical measures on  sepal width and length

5. after cleaning the data ,save the file as 'cleaned_iris.txt' and load to jupyter again to display the values

In [5]:
import numpy as np

In [6]:
iris = np.genfromtxt(r"C:\Users\hi\Downloads\Iris_clean_-_Copy.csv",dtype = 'float16',delimiter = ",")

In [7]:
iris

array([[      nan,       nan,       nan,       nan],
       [5.102e+00, 3.500e+00, 1.400e+00, 2.000e-01],
       [4.898e+00, 3.000e+00, 1.400e+00, 2.000e-01],
       [4.699e+00, 3.199e+00, 1.300e+00, 2.000e-01],
       [4.602e+00, 3.100e+00, 1.500e+00, 1.020e+01],
       [5.000e+01, 3.600e+00, 1.400e+00, 2.000e-01],
       [5.398e+00,       nan, 1.700e+00, 3.999e-01],
       [4.602e+00, 3.400e+00, 1.400e+00, 3.000e-01],
       [5.000e+00, 3.400e+00, 1.500e+00, 2.000e-01],
       [4.398e+00, 2.900e+00, 1.400e+00, 2.000e-01],
       [4.898e+00, 3.100e+00,       nan, 9.998e-02],
       [5.398e+00, 3.699e+00, 1.500e+00, 2.000e-01],
       [4.801e+00, 3.400e+00, 1.600e+00, 2.000e-01],
       [4.801e+00, 1.300e+02, 1.400e+00, 1.010e+01],
       [4.301e+00, 3.000e+00, 1.100e+00, 9.998e-02],
       [5.801e+00, 4.000e+00, 1.200e+00, 2.000e-01],
       [5.699e+00, 4.398e+00, 1.500e+00, 3.999e-01],
       [5.041e+01,       nan, 1.300e+00, 3.999e-01],
       [5.102e+00, 3.500e+00, 1.400e+00, 3.000

In [8]:
sepal_width= iris[1:,1]
sepal_width

array([  3.5,   3. ,   3.2,   3.1,   3.6,   nan,   3.4,   3.4,   2.9,
         3.1,   3.7,   3.4, 130. ,   3. ,   4. ,   4.4,   nan,   3.5,
         3.8,   3.8,   3.4,   3.7,   3.6,   3.3,   3.4,   3. ,  34. ,
         3.5,   3.4,   3.2,   3.1,   3.4,   4.1,   4.2,   3.1,   3.2,
         3.5,   3.1,   3. ,   3.4,   3.5,   2.3,   3.2,   3.5,   3.8,
         3. ,   3.8,   3.2,   3.7,   3.3,   3.2,   3.2,   nan,   2.3,
         2.8,   2.8,   3.3,   2.4,   2.9,   2.7,   2. ,   3. ,   2.2,
         2.9,   2.9,   3.1,   3. ,   2.7,   2.2,   2.5,   3.2,   2.8,
         2.5,   nan,   2.9,   3. ,   2.8,   3. ,   2.9,   2.6,   2.4,
         2.4,   2.7,   2.7,   3. ,   3.4,   3.1,   2.3,   3. ,   2.5,
         2.6,   3. , 112.6,   2.3,   2.7,   3. ,   2.9,   2.9,   2.5,
         2.8,   3.3,   2.7,   3. ,   2.9,   3. ,   3. ,   2.5,   2.9,
         2.5,   3.6,   3.2,   2.7,   3. ,   2.5,   2.8,   3.2,   3. ,
         3.8,   2.6,   2.2,   3.2,   2.8,   2.8,   2.7,   3.3,   3.2,
         2.8,   3. ,

In [9]:
np.nanmedian(sepal_width) #median

3.0

In [11]:
sepal_width = np.where(np.isnan(sepal_width),3,sepal_width)  #missing values
sepal_width

array([  3.5,   3. ,   3.2,   3.1,   3.6,   3. ,   3.4,   3.4,   2.9,
         3.1,   3.7,   3.4, 130. ,   3. ,   4. ,   4.4,   3. ,   3.5,
         3.8,   3.8,   3.4,   3.7,   3.6,   3.3,   3.4,   3. ,  34. ,
         3.5,   3.4,   3.2,   3.1,   3.4,   4.1,   4.2,   3.1,   3.2,
         3.5,   3.1,   3. ,   3.4,   3.5,   2.3,   3.2,   3.5,   3.8,
         3. ,   3.8,   3.2,   3.7,   3.3,   3.2,   3.2,   3. ,   2.3,
         2.8,   2.8,   3.3,   2.4,   2.9,   2.7,   2. ,   3. ,   2.2,
         2.9,   2.9,   3.1,   3. ,   2.7,   2.2,   2.5,   3.2,   2.8,
         2.5,   3. ,   2.9,   3. ,   2.8,   3. ,   2.9,   2.6,   2.4,
         2.4,   2.7,   2.7,   3. ,   3.4,   3.1,   2.3,   3. ,   2.5,
         2.6,   3. , 112.6,   2.3,   2.7,   3. ,   2.9,   2.9,   2.5,
         2.8,   3.3,   2.7,   3. ,   2.9,   3. ,   3. ,   2.5,   2.9,
         2.5,   3.6,   3.2,   2.7,   3. ,   2.5,   2.8,   3.2,   3. ,
         3.8,   2.6,   2.2,   3.2,   2.8,   2.8,   2.7,   3.3,   3.2,
         2.8,   3. ,

In [12]:
outlier_sepal_width = len(sepal_width[sepal_width>6]) #no.of outliers in sepal width
outlier_sepal_width

3

In [13]:
final_sepal_width = np.where(sepal_width>6,4,sepal_width)
final_sepal_width

array([3.5, 3. , 3.2, 3.1, 3.6, 3. , 3.4, 3.4, 2.9, 3.1, 3.7, 3.4, 4. ,
       3. , 4. , 4.4, 3. , 3.5, 3.8, 3.8, 3.4, 3.7, 3.6, 3.3, 3.4, 3. ,
       4. , 3.5, 3.4, 3.2, 3.1, 3.4, 4.1, 4.2, 3.1, 3.2, 3.5, 3.1, 3. ,
       3.4, 3.5, 2.3, 3.2, 3.5, 3.8, 3. , 3.8, 3.2, 3.7, 3.3, 3.2, 3.2,
       3. , 2.3, 2.8, 2.8, 3.3, 2.4, 2.9, 2.7, 2. , 3. , 2.2, 2.9, 2.9,
       3.1, 3. , 2.7, 2.2, 2.5, 3.2, 2.8, 2.5, 3. , 2.9, 3. , 2.8, 3. ,
       2.9, 2.6, 2.4, 2.4, 2.7, 2.7, 3. , 3.4, 3.1, 2.3, 3. , 2.5, 2.6,
       3. , 4. , 2.3, 2.7, 3. , 2.9, 2.9, 2.5, 2.8, 3.3, 2.7, 3. , 2.9,
       3. , 3. , 2.5, 2.9, 2.5, 3.6, 3.2, 2.7, 3. , 2.5, 2.8, 3.2, 3. ,
       3.8, 2.6, 2.2, 3.2, 2.8, 2.8, 2.7, 3.3, 3.2, 2.8, 3. , 2.8, 3. ,
       2.8, 3.8, 2.8, 2.8, 2.6, 3. , 3.4, 3. , 3. , 3.1, 3.1, 3.1, 2.7,
       3.2, 3.3, 3. , 2.5, 3. , 3.4, 3. , 2.8, 2.8, 2.7, 3.3, 3.2, 2.5,
       2.9, 2.5, 3. , 2.8, 2.8, 2.7, 3.6, 3.2, 2.7], dtype=float16)

### sorting sepal width

In [14]:
np.sort(final_sepal_width)

array([2. , 2.2, 2.2, 2.2, 2.3, 2.3, 2.3, 2.3, 2.4, 2.4, 2.4, 2.5, 2.5,
       2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.6, 2.6, 2.6, 2.6, 2.7,
       2.7, 2.7, 2.7, 2.7, 2.7, 2.7, 2.7, 2.7, 2.7, 2.7, 2.7, 2.8, 2.8,
       2.8, 2.8, 2.8, 2.8, 2.8, 2.8, 2.8, 2.8, 2.8, 2.8, 2.8, 2.8, 2.8,
       2.8, 2.8, 2.9, 2.9, 2.9, 2.9, 2.9, 2.9, 2.9, 2.9, 2.9, 2.9, 2.9,
       3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. ,
       3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. ,
       3. , 3. , 3. , 3. , 3. , 3.1, 3.1, 3.1, 3.1, 3.1, 3.1, 3.1, 3.1,
       3.1, 3.1, 3.2, 3.2, 3.2, 3.2, 3.2, 3.2, 3.2, 3.2, 3.2, 3.2, 3.2,
       3.2, 3.2, 3.2, 3.2, 3.3, 3.3, 3.3, 3.3, 3.3, 3.3, 3.3, 3.4, 3.4,
       3.4, 3.4, 3.4, 3.4, 3.4, 3.4, 3.4, 3.4, 3.4, 3.5, 3.5, 3.5, 3.5,
       3.5, 3.5, 3.6, 3.6, 3.6, 3.6, 3.7, 3.7, 3.7, 3.8, 3.8, 3.8, 3.8,
       3.8, 3.8, 4. , 4. , 4. , 4. , 4.1, 4.2, 4.4], dtype=float16)

In [15]:
np.mean(final_sepal_width)  #mean of sepal width

3.047

In [16]:
np.median(final_sepal_width) #median of sepal width

3.0

In [17]:
np.max(final_sepal_width) 

4.4

In [18]:
np.min(final_sepal_width) 

2.0

In [19]:
range = np.max(final_sepal_width)-np.min(final_sepal_width)
range

2.398

In [20]:
np.var(final_sepal_width)

0.1852

In [21]:
np.std(final_sepal_width)

0.4304

In [22]:
np.savetxt("cleaned_sepalwidth",final_sepal_width)

In [24]:
np.loadtxt("cleaned_sepalwidth")

array([3.5       , 3.        , 3.19921875, 3.09960938, 3.59960938,
       3.        , 3.40039062, 3.40039062, 2.90039062, 3.09960938,
       3.69921875, 3.40039062, 4.        , 3.        , 4.        ,
       4.3984375 , 3.        , 3.5       , 3.80078125, 3.80078125,
       3.40039062, 3.69921875, 3.59960938, 3.30078125, 3.40039062,
       3.        , 4.        , 3.5       , 3.40039062, 3.19921875,
       3.09960938, 3.40039062, 4.1015625 , 4.19921875, 3.09960938,
       3.19921875, 3.5       , 3.09960938, 3.        , 3.40039062,
       3.5       , 2.30078125, 3.19921875, 3.5       , 3.80078125,
       3.        , 3.80078125, 3.19921875, 3.69921875, 3.30078125,
       3.19921875, 3.19921875, 3.        , 2.30078125, 2.80078125,
       2.80078125, 3.30078125, 2.40039062, 2.90039062, 2.69921875,
       2.        , 3.        , 2.19921875, 2.90039062, 2.90039062,
       3.09960938, 3.        , 2.69921875, 2.19921875, 2.5       ,
       3.19921875, 2.80078125, 2.5       , 3.        , 2.90039

### sepal length

In [25]:
sepal_length = iris[1:,0]
sepal_length

array([  5.1,   4.9,   4.7,   4.6,  50. ,   5.4,   4.6,   5. ,   4.4,
         4.9,   5.4,   4.8,   4.8,   4.3,   5.8,   5.7,  50.4,   5.1,
         5.7,   5.1,   5.4,   5.1,   4.6,   5.1,   4.8,   5. ,   5. ,
         5.2,   5.2,   4.7,   4.8,   5.4,   5.2,   5.5,   4.9,   5. ,
         5.5,   4.9,   4.4,   5.1,   5. ,   4.5,   4.4,   5. ,   5.1,
         4.8,   5.1,   4.6,   5.3,   5. ,   7. ,   6.4,   6.9,   5.5,
         6.5,   5.7, 116.3,   4.9,   6.6,   5.2,   5. ,   5.9,   6. ,
         6.1,   5.6,   6.7,   5.6,   5.8,   6.2,   5.6,   5.9,   6.1,
         6.3,   6.1,   6.4,   6.6,   6.8,   6.7,   6. ,   5.7,   5.5,
         5.5,   5.8,   6. ,   5.4,   6. ,   6.7,   6.3,   5.6,   5.5,
         5.5,   6.1,   5.8,   5. ,   5.6,   5.7,   5.7,   6.2,   5.1,
         5.7,   6.3,   5.8,   7.1,   6.3,   6.5,   7.6,   4.9,   7.3,
         6.7,   7.2,   6.5,   6.4,   6.8,   5.7,   5.8,   6.4,   6.5,
         7.7,   7.7,   6. ,   6.9,   5.6,   7.7,   6.3,   6.7,   7.2,
         6.2,   6.1,

In [26]:
np.nanmedian(sepal_length)

5.8

In [27]:
sepal_length = np.where(np.isnan(sepal_length),np.nanmedian(sepal_length),sepal_length)  
sepal_length

array([  5.1,   4.9,   4.7,   4.6,  50. ,   5.4,   4.6,   5. ,   4.4,
         4.9,   5.4,   4.8,   4.8,   4.3,   5.8,   5.7,  50.4,   5.1,
         5.7,   5.1,   5.4,   5.1,   4.6,   5.1,   4.8,   5. ,   5. ,
         5.2,   5.2,   4.7,   4.8,   5.4,   5.2,   5.5,   4.9,   5. ,
         5.5,   4.9,   4.4,   5.1,   5. ,   4.5,   4.4,   5. ,   5.1,
         4.8,   5.1,   4.6,   5.3,   5. ,   7. ,   6.4,   6.9,   5.5,
         6.5,   5.7, 116.3,   4.9,   6.6,   5.2,   5. ,   5.9,   6. ,
         6.1,   5.6,   6.7,   5.6,   5.8,   6.2,   5.6,   5.9,   6.1,
         6.3,   6.1,   6.4,   6.6,   6.8,   6.7,   6. ,   5.7,   5.5,
         5.5,   5.8,   6. ,   5.4,   6. ,   6.7,   6.3,   5.6,   5.5,
         5.5,   6.1,   5.8,   5. ,   5.6,   5.7,   5.7,   6.2,   5.1,
         5.7,   6.3,   5.8,   7.1,   6.3,   6.5,   7.6,   4.9,   7.3,
         6.7,   7.2,   6.5,   6.4,   6.8,   5.7,   5.8,   6.4,   6.5,
         7.7,   7.7,   6. ,   6.9,   5.6,   7.7,   6.3,   6.7,   7.2,
         6.2,   6.1,

In [28]:
outlier_sepal_length = len(sepal_length[sepal_length>8]) 
outlier_sepal_length

4

In [29]:
final_sepal_length = np.where(sepal_length>8,6,sepal_length)  
final_sepal_length

array([5.1, 4.9, 4.7, 4.6, 6. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
       4.3, 5.8, 5.7, 6. , 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5. ,
       5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9, 4.4,
       5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 7. , 6.4,
       6.9, 5.5, 6.5, 5.7, 6. , 4.9, 6.6, 5.2, 5. , 5.9, 6. , 6.1, 5.6,
       6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8, 6.7,
       6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 6.7, 6.3, 5.6, 5.5, 5.5,
       6.1, 5.8, 5. , 5.6, 5.7, 5.7, 6.2, 5.1, 5.7, 6.3, 5.8, 7.1, 6.3,
       6.5, 7.6, 4.9, 7.3, 6.7, 7.2, 6.5, 6.4, 6.8, 5.7, 5.8, 6.4, 6.5,
       7.7, 7.7, 6. , 6.9, 5.6, 7.7, 6.3, 6.7, 7.2, 6.2, 6.1, 6.4, 6. ,
       5.8, 5.8, 6.4, 6.3, 6.1, 7.7, 6.3, 6.4, 6. , 6.9, 6.7, 6.9, 5.8,
       6.8, 6.7, 6.7, 6.3, 6.5, 6.2, 5.9, 5.6, 7.7, 5.8, 5.8, 7.2, 4.9,
       7.3, 6.7, 5.9, 5.6, 7.7, 6.3, 7.2, 6.5, 6.4], dtype=float16)

In [30]:
np.mean(final_sepal_length)

5.875

In [31]:
np.median(final_sepal_length)

5.8

In [32]:
np.max(final_sepal_length)

7.7

In [33]:
np.min(final_sepal_length)

4.3

In [34]:
range2 = np.max(final_sepal_length)-np.min(final_sepal_length)
range2

3.398

In [35]:
np.var(final_sepal_length)

0.654

In [36]:
np.std(final_sepal_length)

0.8086

In [37]:
np.savetxt("cleaned_sepallength",final_sepal_length)

In [38]:
np.loadtxt("cleaned_sepallength")

array([5.1015625 , 4.8984375 , 4.69921875, 4.6015625 , 6.        ,
       5.3984375 , 4.6015625 , 5.        , 4.3984375 , 4.8984375 ,
       5.3984375 , 4.80078125, 4.80078125, 4.30078125, 5.80078125,
       5.69921875, 6.        , 5.1015625 , 5.69921875, 5.1015625 ,
       5.3984375 , 5.1015625 , 4.6015625 , 5.1015625 , 4.80078125,
       5.        , 5.        , 5.19921875, 5.19921875, 4.69921875,
       4.80078125, 5.3984375 , 5.19921875, 5.5       , 4.8984375 ,
       5.        , 5.5       , 4.8984375 , 4.3984375 , 5.1015625 ,
       5.        , 4.5       , 4.3984375 , 5.        , 5.1015625 ,
       4.80078125, 5.1015625 , 4.6015625 , 5.30078125, 5.        ,
       7.        , 6.3984375 , 6.8984375 , 5.5       , 6.5       ,
       5.69921875, 6.        , 4.8984375 , 6.6015625 , 5.19921875,
       5.        , 5.8984375 , 6.        , 6.1015625 , 5.6015625 ,
       6.69921875, 5.6015625 , 5.80078125, 6.19921875, 5.6015625 ,
       5.8984375 , 6.1015625 , 6.30078125, 6.1015625 , 6.39843

### petal length

In [39]:
petal_length= iris[1:,2]
petal_length

array([ 1.4,  1.4,  1.3,  1.5,  1.4,  1.7,  1.4,  1.5,  1.4,  nan,  1.5,
        1.6,  1.4,  1.1,  1.2,  1.5,  1.3,  1.4,  1.7,  1.5,  1.7,  1.5,
        1. ,  1.7,  1.9,  1.6,  1.6,  1.5,  1.4,  1.6,  1.6,  1.5,  1.5,
        1.4,  1.5,  1.2,  1.3,  1.5,  1.3,  1.5,  1.3, 13. ,  1.3,  1.6,
        1.9,  1.4,  1.6,  1.4,  1.5,  1.4,  4.7,  4.5,  4.9,  4. ,  4.6,
        4.5,  4.7,  3.3,  4.6,  3.9,  3.5,  4.2,  4. ,  4.7,  3.6,  4.4,
        4.5,  4.1,  4.5,  3.9,  4.8,  4. ,  4.9,  4.7,  4.3,  4.4,  4.8,
        5. ,  4.5,  3.5, 13.8,  3.7,  3.9,  5.1,  4.5,  4.5,  4.7,  4.4,
        4.1,  4. ,  4.4,  nan,  4. ,  3.3,  4.2,  4.2,  4.2,  4.3,  3. ,
        4.1,  6. ,  5.1,  5.9,  5.6,  5.8,  6.6,  4.5,  6.3,  5.8,  6.1,
        5.1,  5.3,  nan,  5. ,  5.1,  5.3,  5.5,  6.7,  6.9,  5. ,  5.7,
        4.9,  6.7,  4.9,  5.7,  6. ,  4.8,  4.9,  5.6,  5.8,  6.1,  nan,
        5.6,  5.1,  5.6,  6.1,  5.6,  5.5,  4.8,  5.4,  nan,  5.1,  5.1,
        5.9,  5.7,  nan,  5. ,  5.2,  5.4,  5.1,  4

In [40]:
np.nanmedian(petal_length)

4.5

In [41]:
petal_length = np.where(np.isnan(petal_length),np.nanmedian(petal_length),petal_length)
petal_length

array([ 1.4,  1.4,  1.3,  1.5,  1.4,  1.7,  1.4,  1.5,  1.4,  4.5,  1.5,
        1.6,  1.4,  1.1,  1.2,  1.5,  1.3,  1.4,  1.7,  1.5,  1.7,  1.5,
        1. ,  1.7,  1.9,  1.6,  1.6,  1.5,  1.4,  1.6,  1.6,  1.5,  1.5,
        1.4,  1.5,  1.2,  1.3,  1.5,  1.3,  1.5,  1.3, 13. ,  1.3,  1.6,
        1.9,  1.4,  1.6,  1.4,  1.5,  1.4,  4.7,  4.5,  4.9,  4. ,  4.6,
        4.5,  4.7,  3.3,  4.6,  3.9,  3.5,  4.2,  4. ,  4.7,  3.6,  4.4,
        4.5,  4.1,  4.5,  3.9,  4.8,  4. ,  4.9,  4.7,  4.3,  4.4,  4.8,
        5. ,  4.5,  3.5, 13.8,  3.7,  3.9,  5.1,  4.5,  4.5,  4.7,  4.4,
        4.1,  4. ,  4.4,  4.5,  4. ,  3.3,  4.2,  4.2,  4.2,  4.3,  3. ,
        4.1,  6. ,  5.1,  5.9,  5.6,  5.8,  6.6,  4.5,  6.3,  5.8,  6.1,
        5.1,  5.3,  4.5,  5. ,  5.1,  5.3,  5.5,  6.7,  6.9,  5. ,  5.7,
        4.9,  6.7,  4.9,  5.7,  6. ,  4.8,  4.9,  5.6,  5.8,  6.1,  4.5,
        5.6,  5.1,  5.6,  6.1,  5.6,  5.5,  4.8,  5.4,  4.5,  5.1,  5.1,
        5.9,  5.7,  4.5,  5. ,  5.2,  5.4,  5.1,  4

In [42]:
outlier_petal_length = len(petal_length[petal_length>7])
outlier_petal_length

2

In [43]:
final_petal_length = np.where(petal_length>7,5,petal_length)
final_petal_length

array([1.4, 1.4, 1.3, 1.5, 1.4, 1.7, 1.4, 1.5, 1.4, 4.5, 1.5, 1.6, 1.4,
       1.1, 1.2, 1.5, 1.3, 1.4, 1.7, 1.5, 1.7, 1.5, 1. , 1.7, 1.9, 1.6,
       1.6, 1.5, 1.4, 1.6, 1.6, 1.5, 1.5, 1.4, 1.5, 1.2, 1.3, 1.5, 1.3,
       1.5, 1.3, 5. , 1.3, 1.6, 1.9, 1.4, 1.6, 1.4, 1.5, 1.4, 4.7, 4.5,
       4.9, 4. , 4.6, 4.5, 4.7, 3.3, 4.6, 3.9, 3.5, 4.2, 4. , 4.7, 3.6,
       4.4, 4.5, 4.1, 4.5, 3.9, 4.8, 4. , 4.9, 4.7, 4.3, 4.4, 4.8, 5. ,
       4.5, 3.5, 5. , 3.7, 3.9, 5.1, 4.5, 4.5, 4.7, 4.4, 4.1, 4. , 4.4,
       4.5, 4. , 3.3, 4.2, 4.2, 4.2, 4.3, 3. , 4.1, 6. , 5.1, 5.9, 5.6,
       5.8, 6.6, 4.5, 6.3, 5.8, 6.1, 5.1, 5.3, 4.5, 5. , 5.1, 5.3, 5.5,
       6.7, 6.9, 5. , 5.7, 4.9, 6.7, 4.9, 5.7, 6. , 4.8, 4.9, 5.6, 5.8,
       6.1, 4.5, 5.6, 5.1, 5.6, 6.1, 5.6, 5.5, 4.8, 5.4, 4.5, 5.1, 5.1,
       5.9, 5.7, 4.5, 5. , 5.2, 5.4, 5.1, 4.9, 6.7, 4.9, 5.7, 6. , 4.5,
       6.3, 5.8, 5.1, 4.9, 6.7, 4.9, 6.1, 5.1, 5.3], dtype=float16)

In [44]:
np.mean(final_petal_length)

3.938

In [45]:
np.median(final_petal_length)

4.5

In [46]:
np.var(final_petal_length)

2.979

In [47]:
np.std(final_petal_length)

1.726

In [48]:
np.max(final_petal_length)

6.9

In [49]:
np.min(final_petal_length)

1.0

In [50]:
range3 = np.max(final_petal_length)-np.min(final_petal_length)
range3

5.9

In [51]:
np.savetxt("cleaned_petallength",final_petal_length)

In [52]:
np.loadtxt("cleaned_petallength")

array([1.40039062, 1.40039062, 1.29980469, 1.5       , 1.40039062,
       1.70019531, 1.40039062, 1.5       , 1.40039062, 4.5       ,
       1.5       , 1.59960938, 1.40039062, 1.09960938, 1.20019531,
       1.5       , 1.29980469, 1.40039062, 1.70019531, 1.5       ,
       1.70019531, 1.5       , 1.        , 1.70019531, 1.90039062,
       1.59960938, 1.59960938, 1.5       , 1.40039062, 1.59960938,
       1.59960938, 1.5       , 1.5       , 1.40039062, 1.5       ,
       1.20019531, 1.29980469, 1.5       , 1.29980469, 1.5       ,
       1.29980469, 5.        , 1.29980469, 1.59960938, 1.90039062,
       1.40039062, 1.59960938, 1.40039062, 1.5       , 1.40039062,
       4.69921875, 4.5       , 4.8984375 , 4.        , 4.6015625 ,
       4.5       , 4.69921875, 3.30078125, 4.6015625 , 3.90039062,
       3.5       , 4.19921875, 4.        , 4.69921875, 3.59960938,
       4.3984375 , 4.5       , 4.1015625 , 4.5       , 3.90039062,
       4.80078125, 4.        , 4.8984375 , 4.69921875, 4.30078

### petal width

In [53]:
petal_width = iris[1:,3]
petal_width

array([2.000e-01, 2.000e-01, 2.000e-01, 1.020e+01, 2.000e-01, 3.999e-01,
       3.000e-01, 2.000e-01, 2.000e-01, 9.998e-02, 2.000e-01, 2.000e-01,
       1.010e+01, 9.998e-02, 2.000e-01, 3.999e-01, 3.999e-01, 3.000e-01,
       3.000e-01, 3.000e-01, 2.000e-01, 3.999e-01, 2.000e-01, 5.000e-01,
       2.000e-01, 2.000e-01, 3.999e-01, 2.000e-01, 1.102e+02, 2.000e-01,
       2.000e-01, 3.999e-01, 9.998e-02, 2.000e-01, 9.998e-02, 2.000e-01,
       2.000e-01, 9.998e-02, 2.000e-01, 2.000e-01, 3.000e-01, 3.000e-01,
       2.000e-01, 6.001e-01, 3.999e-01, 3.000e-01, 2.000e-01, 2.000e-01,
       2.000e-01, 2.000e-01, 1.400e+00, 1.500e+00, 1.500e+00, 1.300e+00,
       1.500e+00, 1.300e+00, 1.600e+00, 1.600e+01, 1.300e+00, 1.400e+00,
       1.000e+00, 1.500e+00, 1.000e+00, 1.400e+00, 1.300e+00, 1.400e+00,
       1.500e+00, 1.000e+00, 1.500e+00, 1.100e+00, 1.800e+00, 1.300e+00,
       1.500e+00, 1.200e+00, 1.300e+00, 1.400e+00, 1.400e+00, 1.700e+00,
       1.500e+00, 1.000e+00, 1.100e+00, 1.000e+00, 

In [54]:
np.nanmedian(petal_width)

1.5

In [55]:
petal_width = np.where(np.isnan(petal_width),np.nanmedian(petal_width ),petal_width )
petal_width

array([2.000e-01, 2.000e-01, 2.000e-01, 1.020e+01, 2.000e-01, 3.999e-01,
       3.000e-01, 2.000e-01, 2.000e-01, 9.998e-02, 2.000e-01, 2.000e-01,
       1.010e+01, 9.998e-02, 2.000e-01, 3.999e-01, 3.999e-01, 3.000e-01,
       3.000e-01, 3.000e-01, 2.000e-01, 3.999e-01, 2.000e-01, 5.000e-01,
       2.000e-01, 2.000e-01, 3.999e-01, 2.000e-01, 1.102e+02, 2.000e-01,
       2.000e-01, 3.999e-01, 9.998e-02, 2.000e-01, 9.998e-02, 2.000e-01,
       2.000e-01, 9.998e-02, 2.000e-01, 2.000e-01, 3.000e-01, 3.000e-01,
       2.000e-01, 6.001e-01, 3.999e-01, 3.000e-01, 2.000e-01, 2.000e-01,
       2.000e-01, 2.000e-01, 1.400e+00, 1.500e+00, 1.500e+00, 1.300e+00,
       1.500e+00, 1.300e+00, 1.600e+00, 1.600e+01, 1.300e+00, 1.400e+00,
       1.000e+00, 1.500e+00, 1.000e+00, 1.400e+00, 1.300e+00, 1.400e+00,
       1.500e+00, 1.000e+00, 1.500e+00, 1.100e+00, 1.800e+00, 1.300e+00,
       1.500e+00, 1.200e+00, 1.300e+00, 1.400e+00, 1.400e+00, 1.700e+00,
       1.500e+00, 1.000e+00, 1.100e+00, 1.000e+00, 

In [56]:
outliers_petal_width = len(petal_width[petal_width>3])
outliers_petal_width

5

In [57]:
final_petal_width = np.where(petal_width>3,2,petal_width)
final_petal_width

array([0.2, 0.2, 0.2, 2. , 0.2, 0.4, 0.3, 0.2, 0.2, 0.1, 0.2, 0.2, 2. ,
       0.1, 0.2, 0.4, 0.4, 0.3, 0.3, 0.3, 0.2, 0.4, 0.2, 0.5, 0.2, 0.2,
       0.4, 0.2, 2. , 0.2, 0.2, 0.4, 0.1, 0.2, 0.1, 0.2, 0.2, 0.1, 0.2,
       0.2, 0.3, 0.3, 0.2, 0.6, 0.4, 0.3, 0.2, 0.2, 0.2, 0.2, 1.4, 1.5,
       1.5, 1.3, 1.5, 1.3, 1.6, 2. , 1.3, 1.4, 1. , 1.5, 1. , 1.4, 1.3,
       1.4, 1.5, 1. , 1.5, 1.1, 1.8, 1.3, 1.5, 1.2, 1.3, 1.4, 1.4, 1.7,
       1.5, 1. , 1.1, 1. , 1.2, 1.6, 1.5, 1.6, 1.5, 1.3, 1.3, 1.3, 1.2,
       1.4, 1.2, 1. , 1.3, 1.2, 1.3, 1.3, 2. , 1.3, 2.5, 1.9, 2.1, 1.8,
       2.2, 2.1, 1.7, 1.8, 1.8, 2.5, 2. , 1.9, 2.1, 2. , 2.4, 2.3, 1.8,
       2.2, 2.3, 1.5, 2.3, 2. , 2. , 1.8, 2.1, 1.8, 1.8, 1.8, 2.1, 1.6,
       1.9, 2. , 2.2, 1.5, 1.4, 2.3, 2.4, 1.8, 1.8, 2.1, 2.4, 2.3, 1.9,
       2.3, 2.5, 2.3, 1.9, 2. , 2.3, 1.8, 2. , 2. , 1.8, 2.1, 1.8, 1.7,
       1.8, 1.8, 1.8, 2. , 2. , 1.8, 2.5, 2. , 1.9], dtype=float16)

In [58]:
np.savetxt("cleaned_petalwidth",final_petal_width)

In [59]:
np.loadtxt("cleaned_petalwidth")

array([0.19995117, 0.19995117, 0.19995117, 2.        , 0.19995117,
       0.39990234, 0.30004883, 0.19995117, 0.19995117, 0.09997559,
       0.19995117, 0.19995117, 2.        , 0.09997559, 0.19995117,
       0.39990234, 0.39990234, 0.30004883, 0.30004883, 0.30004883,
       0.19995117, 0.39990234, 0.19995117, 0.5       , 0.19995117,
       0.19995117, 0.39990234, 0.19995117, 2.        , 0.19995117,
       0.19995117, 0.39990234, 0.09997559, 0.19995117, 0.09997559,
       0.19995117, 0.19995117, 0.09997559, 0.19995117, 0.19995117,
       0.30004883, 0.30004883, 0.19995117, 0.60009766, 0.39990234,
       0.30004883, 0.19995117, 0.19995117, 0.19995117, 0.19995117,
       1.40039062, 1.5       , 1.5       , 1.29980469, 1.5       ,
       1.29980469, 1.59960938, 2.        , 1.29980469, 1.40039062,
       1.        , 1.5       , 1.        , 1.40039062, 1.29980469,
       1.40039062, 1.5       , 1.        , 1.5       , 1.09960938,
       1.79980469, 1.29980469, 1.5       , 1.20019531, 1.29980

### after cleaning the data save the file as "cleaned_Iris.txt" 

In [72]:
new_iris = np.array([final_sepal_length,final_sepal_width,final_petal_length,final_petal_width]).reshape(4,165)

In [73]:
np.savetxt("cleaned_iris.txt",new_iris)

In [74]:
np.loadtxt("cleaned_iris.txt")

array([[5.1015625 , 4.8984375 , 4.69921875, 4.6015625 , 6.        ,
        5.3984375 , 4.6015625 , 5.        , 4.3984375 , 4.8984375 ,
        5.3984375 , 4.80078125, 4.80078125, 4.30078125, 5.80078125,
        5.69921875, 6.        , 5.1015625 , 5.69921875, 5.1015625 ,
        5.3984375 , 5.1015625 , 4.6015625 , 5.1015625 , 4.80078125,
        5.        , 5.        , 5.19921875, 5.19921875, 4.69921875,
        4.80078125, 5.3984375 , 5.19921875, 5.5       , 4.8984375 ,
        5.        , 5.5       , 4.8984375 , 4.3984375 , 5.1015625 ,
        5.        , 4.5       , 4.3984375 , 5.        , 5.1015625 ,
        4.80078125, 5.1015625 , 4.6015625 , 5.30078125, 5.        ,
        7.        , 6.3984375 , 6.8984375 , 5.5       , 6.5       ,
        5.69921875, 6.        , 4.8984375 , 6.6015625 , 5.19921875,
        5.        , 5.8984375 , 6.        , 6.1015625 , 5.6015625 ,
        6.69921875, 5.6015625 , 5.80078125, 6.19921875, 5.6015625 ,
        5.8984375 , 6.1015625 , 6.30078125, 6.10