In [1]:
import numpy as np

# Creating an array

In [3]:
num = np.array([2,4,6,8,10,12,14,16,20])
num

array([ 2,  4,  6,  8, 10, 12, 14, 16, 20])

In [4]:
num1 = [1,2,12,15,17,22]

In [6]:
n = np.array(num1)
n

array([ 1,  2, 12, 15, 17, 22])

In [7]:
tuple1 = (1,15,22,24,16,19,27)

In [8]:
np.array(tuple1)

array([ 1, 15, 22, 24, 16, 19, 27])

In [9]:
np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
np.ones(12)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [13]:
np.arange(1,29)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28])

In [14]:
np.linspace(0,5,20)

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

### 2. Create a 1D NumPy array containing the first 12 positive integer as arr1

In [16]:
arr1 = np.array(range(1,13))
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

### Create an array containing 20 elements from 0 to 12 using linspace

In [21]:
array2 = np.linspace(0,12,20)
array2

array([ 0.        ,  0.63157895,  1.26315789,  1.89473684,  2.52631579,
        3.15789474,  3.78947368,  4.42105263,  5.05263158,  5.68421053,
        6.31578947,  6.94736842,  7.57894737,  8.21052632,  8.84210526,
        9.47368421, 10.10526316, 10.73684211, 11.36842105, 12.        ])

### Find all the attributes of array1 and array2

In [18]:
arr1.dtype

dtype('int32')

In [19]:
arr1.nbytes

48

In [20]:
arr1.ndim

1

In [27]:
arr1.min()

1

In [26]:
arr1.max()

12

In [22]:
array2.dtype

dtype('float64')

In [23]:
array2.nbytes

160

In [24]:
array2.ndim

1

In [28]:
array2.max()

12.0

In [29]:
array2.min()

0.0

### Apply measure and describe the data (attributes and descriptive statistics) to above arrays

In [30]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

###  measure of tendency of arr1

In [40]:
np.mean(arr1)

6.5

In [35]:
np.median(arr1)

6.5

### measure of spread of arr1

In [41]:
# range
np.max(arr1)

12

In [42]:
np.min(arr1)

1

In [43]:
range = np.max(arr1) - np.min(arr1)
range

11

In [44]:
# variance
np.var(arr1)

11.916666666666666

In [45]:
# standard deviation
np.std(arr1)

3.452052529534663

### IQR for arr1

In [46]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [47]:
q1 = np.percentile(arr1,25)
q1

3.75

In [48]:
q2 = np.percentile(arr1,50)
q2

6.5

In [49]:
q3 = np.percentile(arr1,75)
q3

9.25

In [50]:
IQR = q3 - q1
IQR

5.5

In [53]:
lower_limit = q1 - (1.5 * IQR)
lower_limit

-4.5

In [55]:
upper_limit = q3 + (1.5 * IQR)
upper_limit

17.5

### measure of central tendency of array2

In [63]:
np.mean(array2)

5.999999999999999

In [64]:
np.median(array2)

6.0

### measure of spread for array2

In [58]:
# range
np.max(array2)

12.0

In [59]:
np.min(array2)

0.0

In [60]:
range = np.max(array2) - np.min(array2)
range

12.0

In [61]:
### variance
np.var(array2)

13.26315789473684

In [62]:
### standard deviation
np.std(array2)

3.6418618720013036

### IQR for array2

In [72]:
q1 = np.percentile(array2,25)
q1

3.0

In [73]:
q2 = np.percentile(array2,50)
q2

6.0

In [74]:
q3 = np.percentile(array2,75)
q3

9.0

In [68]:
IQR = q3 - q1
IQR

6.0

In [69]:
lower_limit = q1 - (1.5 * IQR)
lower_limit

-6.0

In [71]:
upper_limit = q3 + (1.5 * IQR)
upper_limit

18.0