**Creation of ndarray**

1. Write python code to create 3d array in different ways with 15 elements.
2. Array Creation:
a. Create a 4D NumPy array containing the first 12 positive integers as arr1.
b. Create a 3D NumPy array1 with 20 random elements containing integers between 0 and 1.
3. Find all attributes of array1 and array2
4. Apply measure and describe the data (attributes and descriptive statistics) to above arrays using NumPy.


**Array Slicing and Indexing:**

a. Creating Arrays:
      - Create a 1-dimensional NumPy array  arr1 with the values [0, 11, 26, 73, 42, 51, 6,77, 8,29].
      - Create a 2-dimensional NumPy array  arr2  with the values  [[0, 1, 2], [3, 4, 5], [6, 7, 8]].
      
 b.Basic Indexing:
      - Print the element at index 3 of  arr1.
      - Print the element at row 2, column 1 of  arr2

   c. Array Slicing:
      - Print the first five elements of `arr1`.
      - Print the subarray of `arr2` consisting of the last two rows and the first two columns.
       - Print every second element starting from index 1 up to index 7 of `arr1`.







**Data Type Manipulation**

a. Creating Arrays with Specific Data Types:
      - Create a 1-dimensional NumPy array `int_array` with the values `[1, 2, 3, 4, 5]` and the data type `int16`.
      - Create a 1-dimensional NumPy array `float_array` with the values `[0.1, 0.2, 0.3, 0.4, 0.5]` and the data type `float64`.
      
b. Data Type Conversion:
      - Convert the `float_array` to an array with data type `int32`. Print the result.
      - Convert the `int_array` to an array with data type `float32`. Print the result.

**Generating Random Numbers:**

1.	Use numpy.random.randint() to create an array rand_integers containing 10 random integers between 0 and 100 (inclusive).

2.	Use numpy.random.uniform() to create an array rand_uniform containing 5 random numbers sampled from a uniform distribution between -1 and 1.

3.	Create an array rand_matrix with random integers between 50 and 100 (inclusive).and reshape it to 2-dimensional (4 x 4) matrix

4.	Apply descriptive statistics for rand_matrix.


**Analyze the Data:**

Salaries = [87877, 54494, 54804, 85051, 52453, 31250, 94868, 66349, 39828, 60501, 58570, 74906, 41671, 51428, 56414, 98446, 56819, 82833, 50477, 62898, 99658, 89224, 34225, 79172, 32199, 63795, 90947, 55723, 64557, 3113638]




Describe the data using numpy array.
Measure the following:
1.	How many employees are getting more less than 50000?

2.	Is it following Normal Distribution?

3.	What is the median salary?

4.	What is the range of salaries for this company?

5.	Find the salaries between average salary and 75% of salaries?

6.	How many employees are getting less than 25 % of salaries ?



In [2]:
import numpy as np

In [17]:
array1 = np.array([[[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]]])
array1

array([[[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]]])

In [18]:
array1 = np.array([[[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]]],ndmin=3)
array1

array([[[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]]])

In [19]:
array1.reshape(1,3,5)
array1

array([[[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]]])

In [20]:
array1 = np.arange(1,16).reshape(1,3,5)
array1

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]]])

In [21]:
arr1 = np.arange(1,13).reshape(1,1,4,3)
arr1

array([[[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]]]])

In [22]:
array2 = np.random.rand(20).reshape(1,4,5)
array2

array([[[0.69395208, 0.84992033, 0.71218149, 0.64199686, 0.43673968],
        [0.02438406, 0.6032218 , 0.25317417, 0.44271521, 0.9875729 ],
        [0.29578809, 0.49001196, 0.95394752, 0.19374204, 0.72345519],
        [0.95345183, 0.39029761, 0.67432885, 0.98887351, 0.67204173]]])

### Attributes of arr1

In [23]:
arr1

array([[[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]]]])

In [29]:
arr1.dtype

dtype('int32')

In [24]:
arr1.ndim

4

In [26]:
arr1.size

12

In [27]:
arr1.itemsize

4

In [28]:
arr1.nbytes

48

### Attributes of array2

In [31]:
array2

array([[[0.69395208, 0.84992033, 0.71218149, 0.64199686, 0.43673968],
        [0.02438406, 0.6032218 , 0.25317417, 0.44271521, 0.9875729 ],
        [0.29578809, 0.49001196, 0.95394752, 0.19374204, 0.72345519],
        [0.95345183, 0.39029761, 0.67432885, 0.98887351, 0.67204173]]])

In [32]:
array2.dtype

dtype('float64')

In [33]:
array2.ndim

3

In [34]:
array2.itemsize

8

In [35]:
array2.nbytes

160

In [36]:
array2.size

20

### Applying Descriptive statistics on arr1

In [37]:
arr1

array([[[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]]]])

In [38]:
arr1.mean()

6.5

In [40]:
np.median(arr1)

6.5

In [41]:
arr1.var()

11.916666666666666

In [42]:
arr1.std()

3.452052529534663

In [43]:
range = arr1.max()-arr1.min()
range

11

In [44]:
q1 = np.percentile(arr1,25)
q1

3.75

In [45]:
q3 = np.percentile(arr1,75)
q3

9.25

In [46]:
IQR = q3 - q1
IQR

5.5

In [47]:
lower_limit = q1 - (1.5 * IQR)
lower_limit

-4.5

In [48]:
upper_limit = q3  +  (1.5 * IQR)
upper_limit

17.5

In [49]:
arr1[arr1<lower_limit]

array([], dtype=int32)

In [51]:
arr1[arr1>upper_limit]

array([], dtype=int32)

### Applying Descriptive statistics on array2


In [52]:
array2

array([[[0.69395208, 0.84992033, 0.71218149, 0.64199686, 0.43673968],
        [0.02438406, 0.6032218 , 0.25317417, 0.44271521, 0.9875729 ],
        [0.29578809, 0.49001196, 0.95394752, 0.19374204, 0.72345519],
        [0.95345183, 0.39029761, 0.67432885, 0.98887351, 0.67204173]]])

In [54]:
array2.mean()

0.5990898455683789

In [56]:
np.median(array2)

0.6570192954081466

In [58]:
range = array2.max()-array2.min()
range

0.9644894525512594

In [59]:
array2.var()

0.0739952480289042

In [60]:
array2.std()

0.27202067573790084

In [62]:
q1 = np.percentile(array2,25)
q1

0.42512916178706556

In [63]:
q3 = np.percentile(array2,75)
q3

0.7550714758817063

In [64]:
IQR = q3-q1
IQR

0.32994231409464075

In [65]:
lower_limit = q1 - (1.5*IQR)
lower_limit

-0.0697843093548956

In [66]:
upper_limit = q3 + (1.5*IQR)
upper_limit

1.2499849470236675

In [68]:
array2[array2<lower_limit]

array([], dtype=float64)

In [69]:
array2[array2>upper_limit]

array([], dtype=float64)

### Array Slicing and Indexing:

a. Creating Arrays: - Create a 1-dimensional NumPy array arr1 with the values [0, 11, 26, 73, 42, 51, 6,77, 8,29]. - Create a 2-dimensional NumPy array arr2 with the values [[0, 1, 2], [3, 4, 5], [6, 7, 8]].

b.Basic Indexing: - Print the element at index 3 of arr1. - Print the element at row 2, column 1 of arr2

c. Array Slicing: - Print the first five elements of arr1. - Print the subarray of arr2 consisting of the last two rows and the first two columns. - Print every second element starting from index 1 up to index 7 of arr1.

In [71]:
n1 = np.array([0, 11, 26, 73, 42, 51, 6,77, 8,29])
n1

array([ 0, 11, 26, 73, 42, 51,  6, 77,  8, 29])

In [72]:
n2 = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
n2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [73]:
n1[3]

73

In [74]:
n2[2][1]

7

In [75]:
n1[:5]

array([ 0, 11, 26, 73, 42])

In [76]:
n2[1:,0:2]

array([[3, 4],
       [6, 7]])

In [77]:
n1[1:8]

array([11, 26, 73, 42, 51,  6, 77])

### Data Type Manipulation

a. Creating Arrays with Specific Data Types: - Create a 1-dimensional NumPy array int_array with the values [1, 2, 3, 4, 5] and the data type int16. - Create a 1-dimensional NumPy array float_array with the values [0.1, 0.2, 0.3, 0.4, 0.5] and the data type float64.

b. Data Type Conversion: - Convert the float_array to an array with data type int32. Print the result. - Convert the int_array to an array with data type float32. Print the result.

In [78]:
a = np.array([1, 2, 3, 4, 5],dtype = "int16")

In [80]:
a.dtype

dtype('int16')

In [81]:
a = np.array([0.1, 0.2, 0.3, 0.4, 0.5],dtype = "float64")

In [82]:
a.dtype

dtype('float64')

In [83]:
b = np.array([0.1, 0.2, 0.3, 0.4, 0.5],dtype = "int32")
b.dtype

dtype('int32')

In [84]:
c = np.array([1, 2, 3, 4, 5],dtype = "float32")
c

array([1., 2., 3., 4., 5.], dtype=float32)

### Generating Random Numbers:

Use numpy.random.randint() to create an array rand_integers containing 10 random integers between 0 and 100 (inclusive).

Use numpy.random.uniform() to create an array rand_uniform containing 5 random numbers sampled from a uniform distribution between -1 and 1.

Create an array rand_matrix with random integers between 50 and 100 (inclusive).and reshape it to 2-dimensional (4 x 4) matrix

Apply descriptive statistics for rand_matrix.

In [85]:
n = np.random.randint(0,101,10)
n

array([18, 44, 97, 29,  9, 24, 36, 45, 97, 44])

In [86]:
np.random.uniform(-1,1,5)

array([ 0.43541692, -0.85143422,  0.32525762, -0.44649465,  0.15702274])

In [87]:
rand_matrix = np.random.randint(50,101,16).reshape(4,4)
rand_matrix

array([[78, 94, 80, 79],
       [99, 50, 83, 78],
       [62, 70, 62, 65],
       [82, 73, 68, 89]])

### Descriptive statistics for rand_matrix.

In [88]:
rand_matrix.mean()

75.75

In [89]:
np.median(rand_matrix)

78.0

In [90]:
rand_matrix.max()-rand_matrix.min()
rand_matrix

array([[78, 94, 80, 79],
       [99, 50, 83, 78],
       [62, 70, 62, 65],
       [82, 73, 68, 89]])

In [91]:
rand_matrix.std()

12.341495047197483

In [92]:
rand_matrix.var()

152.3125

In [93]:
q1 = np.percentile(rand_matrix,25)
q1

67.25

In [94]:
q3 = np.percentile(rand_matrix,75)
q3

82.25

In [95]:
IQR = q3-q1
IQR

15.0

In [96]:
lower = q1 - (1.5 * IQR)
lower

44.75

In [97]:
upper = q3 + (1.5 * IQR)
upper

104.75

In [98]:
rand_matrix[rand_matrix < lower]

array([], dtype=int32)

In [99]:
rand_matrix[rand_matrix > upper]

array([], dtype=int32)

### Analyze the Data:

Salaries = [87877, 54494, 54804, 85051, 52453, 31250, 94868, 66349, 39828, 60501, 58570, 74906, 41671, 51428, 56414, 98446, 56819, 82833, 50477, 62898, 99658, 89224, 34225, 79172, 32199, 63795, 90947, 55723, 64557, 3113638]

Describe the data using numpy array. Measure the following: 1. How many employees are getting more less than 50000?

Is it following Normal Distribution?

What is the median salary?

What is the range of salaries for this company?

Find the salaries between average salary and 75% of salaries?

How many employees are getting less than 25 % of salaries ?

In [6]:
salaries = np.array([87877, 54494, 54804, 85051, 52453, 31250, 94868, 66349, 39828, 60501, 58570, 74906, 41671, 51428, 56414, 98446, 56819, 82833, 50477, 62898, 99658, 89224, 34225, 79172, 32199, 63795, 90947, 55723, 64557, 3113638])

In [7]:
salaries[salaries < 50000]

array([31250, 39828, 41671, 34225, 32199])

In [16]:
np.median(salaries)  # median salary

61699.5

In [17]:
salaries.max() - salaries.min() # range

3082388

In [12]:
avg = salaries.mean()
avg

166169.16666666666

In [13]:
q1 = np.percentile(salaries,25)
q1

52963.25

In [14]:
q3 = np.percentile(salaries,75)
q3

84496.5

In [15]:
salaries[(salaries > avg) & (salaries <= q3)]

array([], dtype=int32)

In [19]:
IQR = q3-q1
IQR                   # finding outliers

31533.25

In [20]:
lower = q1 - (1.5 * IQR)
lower

5663.375

In [21]:
upper = q3 + (1.5 * IQR)
upper

131796.375

In [22]:
salaries[salaries<lower]

array([], dtype=int32)

In [23]:
salaries[salaries>upper]

array([3113638])